name:                cabal-downloader-demo
version:             0.1.0.0
github:              "deech/cabal-downloader-demo"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "Aditya Siram, 2019"

extra-source-files:
- README.org

custom-setup:
  dependencies:
  - downloader >= 0.1.0.0 && < 0.2
  - base >= 4.7 && < 5
  - Cabal >= 2.4.0.0 && < 4
  - filepath >= 1.4.0.0 && < 1.5

dependencies:
- base >= 4.7 && < 5
- filepath >= 1.4.0.0 && < 1.5

executables:
  print-json-rfc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
